
# Developed by Hamid.Memar

name: Build Jenova Runtime (Linux-64)

on: [push]

jobs:
  build:
    name: Deploy Jenova Runtime for Linux64
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Add Conda to System path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install Python Dependencies
        run: |
          conda install -y -c defaults -c conda-forge python=3.10 colored flake8 pytest gcc_linux-64 gxx_linux-64

      - name: Install GNU Compiler Collection 13
        run: |
          sudo apt update
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt install gcc-13 g++-13 -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 130 --slave /usr/bin/g++ g++ /usr/bin/g++-13
          sudo update-alternatives --config gcc
          gcc --version

      - name: Install libSSL 1.1.1
        run: |
          sudo apt-get remove libssl3
          sudo apt-get remove libssl-dev
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.23_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
          sudo dpkg -i libssl-dev_1.1.1f-1ubuntu2.23_amd64.deb

      - name: Install 7-zip Extractor
        run: |
          sudo apt-get install p7zip-full -y

      - name: Download and Extract Pre-Built Dependencies
        run: |
          wget https://jenova-framework.github.io/archive/dependencies/Jenova-Runtime-latest-Dependencies-Linux64.7z
          7z x Jenova-Runtime-latest-Dependencies-Linux64.7z -oLibs
          rm Jenova-Runtime-latest-Dependencies-Linux64.7z

      - name: Build Jenova Runtime using GCC13
        run: |
          python3 ./Jenova.Builder.py --compiler gcc --skip-banner

      - name: Verbose Compiled Binary Dependencies
        run: |
          ldd Linux64/Jenova.Runtime.Linux64.so

      - name: Prepare Jenova SDK and Extension
        run: |
          mkdir -p packaging/Jenova/JenovaSDK
          echo "" > packaging/Jenova/JenovaSDK/.gdignore
          cp JenovaSDK.h packaging/Jenova/JenovaSDK/
          cp Jenova.Runtime.gdextension packaging/Jenova/
          cp Linux64/Jenova.Runtime.Linux64.so packaging/Jenova/

      - name: Upload Jenova Runtime Snapshot Build
        uses: actions/upload-artifact@v4
        with:
          name: jenova-runtime-snapshot-linux64
          path: packaging/
          retention-days: 30
