
# Developed by Hamid.Memar

name: Deploy Jenova Runtime (Windows-x64)

on: [push]

jobs:
  win-msvc:
    name: Runtime Build (MS-VC-x64)
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set Up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install requests py7zr colored

      - name: Build Jenova Runtime using MSVC
        run: |
          python3 ./Jenova.Builder.py --skip-packaging --deploy-mode --compiler win-msvc

      - name: Prepare Jenova SDK and Extension
        run: |
          New-Item -ItemType Directory -Path packaging/Jenova/JenovaSDK -Force
          New-Item -ItemType File -Path packaging/Jenova/JenovaSDK/.gdignore -Force
          Copy-Item JenovaSDK.h packaging/Jenova/JenovaSDK/
          Copy-Item Jenova.Runtime.gdextension packaging/Jenova/
          Copy-Item Win64/Jenova.Runtime.Win64.dll packaging/Jenova/
          Copy-Item Win64/Jenova.Runtime.Win64.pdb packaging/Jenova/
          Copy-Item Win64/JenovaSDK/Jenova.SDK.x64.lib -Destination packaging/Jenova/JenovaSDK/Jenova.SDK.x64.lib

      - name: Upload Jenova Runtime Snapshot Build
        uses: actions/upload-artifact@v4
        with:
          name: jenova-runtime-msvc-snapshot-win64
          include-hidden-files: true
          path: packaging/
          retention-days: 30
  win-clangcl:
    name: Runtime Build (MS-LLVM-x64)
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set Up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install requests py7zr colored

      - name: Build Jenova Runtime using LLVM
        run: |
          python3 ./Jenova.Builder.py --skip-packaging --deploy-mode --compiler win-clangcl

      - name: Prepare Jenova SDK and Extension
        run: |
          New-Item -ItemType Directory -Path packaging/Jenova/JenovaSDK -Force
          New-Item -ItemType File -Path packaging/Jenova/JenovaSDK/.gdignore -Force
          Copy-Item JenovaSDK.h packaging/Jenova/JenovaSDK/
          Copy-Item Jenova.Runtime.gdextension packaging/Jenova/
          Copy-Item Win64/Jenova.Runtime.Win64.dll packaging/Jenova/
          Copy-Item Win64/Jenova.Runtime.Win64.pdb packaging/Jenova/
          Copy-Item Win64/JenovaSDK/Jenova.SDK.x64.lib -Destination packaging/Jenova/JenovaSDK/Jenova.SDK.x64.lib

      - name: Upload Jenova Runtime Snapshot Build
        uses: actions/upload-artifact@v4
        with:
          name: jenova-runtime-llvm-snapshot-win64
          include-hidden-files: true
          path: packaging/
          retention-days: 30
  win-gcc:
    name: Runtime Build (MGW-GCC-x64)
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set Up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install requests py7zr colored

      - name: Build Jenova Runtime using GCC
        run: |
          python3 ./Jenova.Builder.py --skip-packaging --deploy-mode --compiler win-gcc

      - name: Prepare Jenova SDK and Extension
        run: |
          New-Item -ItemType Directory -Path packaging/Jenova/JenovaSDK -Force
          New-Item -ItemType File -Path packaging/Jenova/JenovaSDK/.gdignore -Force
          Copy-Item JenovaSDK.h packaging/Jenova/JenovaSDK/
          Copy-Item Jenova.Runtime.gdextension packaging/Jenova/
          Copy-Item Win64/Jenova.Runtime.Win64.dll packaging/Jenova/
          Copy-Item Win64/Jenova.Runtime.Win64.pdb packaging/Jenova/
          Copy-Item Win64/JenovaSDK/Jenova.SDK.x64.a -Destination packaging/Jenova/JenovaSDK/Jenova.SDK.x64.a

      - name: Upload Jenova Runtime Snapshot Build
        uses: actions/upload-artifact@v4
        with:
          name: jenova-runtime-gcc-snapshot-win64
          include-hidden-files: true
          path: packaging/
          retention-days: 30
  win-clang:
    name: Runtime Build (MGW-CLANG-x64)
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set Up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install requests py7zr colored

      - name: Build Jenova Runtime using Clang
        run: |
          python3 ./Jenova.Builder.py --skip-packaging --deploy-mode --compiler win-clang

      - name: Prepare Jenova SDK and Extension
        run: |
          New-Item -ItemType Directory -Path packaging/Jenova/JenovaSDK -Force
          New-Item -ItemType File -Path packaging/Jenova/JenovaSDK/.gdignore -Force
          Copy-Item JenovaSDK.h packaging/Jenova/JenovaSDK/
          Copy-Item Jenova.Runtime.gdextension packaging/Jenova/
          Copy-Item Win64/Jenova.Runtime.Win64.dll packaging/Jenova/
          Copy-Item Win64/Jenova.Runtime.Win64.pdb packaging/Jenova/
          Copy-Item Win64/JenovaSDK/Jenova.SDK.x64.a -Destination packaging/Jenova/JenovaSDK/Jenova.SDK.x64.a

      - name: Upload Jenova Runtime Snapshot Build
        uses: actions/upload-artifact@v4
        with:
          name: jenova-runtime-clang-snapshot-win64
          include-hidden-files: true
          path: packaging/
          retention-days: 30
